spring.application.name=lockermanagementservice


spring.data.mongodb.uri=mongodb+srv://Siranjeevi:cityzen-619@lockerservice.4bvigsy.mongodb.net/lockerDB?retryWrites=true&w=majority&appName=LockerService
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=${SERVER_PORT:4000}
eureka.client.service-url.defaultZone=https://naming-server-service.onrender.com/eureka
logging.level.org.mongodb.driver=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

user.service.url=${USER_SERVICE_URL:http://localhost:7000}
