spring.application.name=lockermanagementservice


spring.data.mongodb.uri=mongodb+srv://Siranjeevi:oOsjRzsWLvOfZqcB@lockerservice.fpdn3w3.mongodb.net/?retryWrites=true&w=majority&appName=lockerservice
